name: CI

on:
  pull_request:
    branches:
      - main
      -
permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies and run tests
        run: mvn clean test

      - name: Get modified files
        id: get_files
        run: |
          git fetch origin main
          git checkout ${{ github.event.pull_request.base.ref }}
          FILES=$(git diff --name-only origin/main...${{ github.sha }} | grep '\.java$')
          echo "files=${FILES}" | tr ' ' '\n' >> $GITHUB_ENV

      - name: Extract coverage data
        id: extract_coverage
        run: |
          FILES="${{ env.files }}"
          COVERAGE_TABLE="| File | Coverage |\n| :--- | :--- |\n"
          for FILE in $FILES; do
            COVERAGE=$(grep -oP "^$FILE,.*?\K[0-9]+(?=%)" jacoco.csv)
            if [ ! -z "$COVERAGE" ]; then
              COVERAGE_TABLE+="| $FILE | $COVERAGE% |\n"
            else
              COVERAGE_TABLE+="| $FILE | No Coverage Data |\n"
            fi
          done
          echo "coverage_table=${COVERAGE_TABLE}" >> $GITHUB_ENV

      - name: Get coverage percentage
        id: coverage
        run: |
          COVERAGE=$(grep -oP '(?<=class="ctr2">)[0-9]+(?=\s*%)' target/site/jacoco/index.html | tail -1)
          echo "coverage=${COVERAGE}" >> $GITHUB_ENV

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/*.xml

      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            | Name                        | Status | Coverage | Updated (UTC)            |
            | :-------------------------- | :----- | :------- | :----------------------- |
            | **JUnit tests**      | ${{ job.status == 'success' && '✅ Passed' || '❌ Failed' }} | ${{ env.coverage }}%  | ${{ github.event.pull_request.updated_at }} |
            ${{ env.coverage_table }}